### PR TITLE
Add `poppler-glib` to poppler rule

### PR DESCRIPTION
**Pull request by pat-s**
To support packages like [Rpoppler](https://cran.r-project.org/web/packages/Rpoppler/index.html)

### CODE REVIEW

**Comment by gaborcsardi** [comment]
We could also have another rule for this, to avoid unneeded stystem packages.

**Comment by pat-s** [comment]
Sure, makes sense. Is this a fixed decision?

**Comment by glin** [comment]
Yeah I think that would be ideal just because of how many automated processes are installing whatever comes back from the DB.

So currently only 2 CRAN packages seem to be using poppler, pdftools with `SystemRequirements`:
```
Poppler C++ API: libpoppler-cpp-dev (deb) or poppler-cpp-devel (rpm), and poppler-data (rpm/deb) package.
```

Rpoppler with `SystemRequirements`:
```
Poppler Glib interface headers and libraries (<http://poppler.freedesktop.org/>) [Debian/Ubuntu: libpoppler-glib-dev, Fedora: poppler-glib-devel]
```

We could copy-paste the existing poppler rule as a new `poppler-glib` rule, that just matches on `"poppler glib"` with the glib packages instead.

Then for the current one, changing it to match on `"Poppler C\\+\\+"` would be an option as I don't see any other CRAN packages that just have "poppler" in their system reqs, but I'm not sure if that would affect any other packages outside CRAN. I'd be fine with leaving the current rule as-is for now.

**Review by glin — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
