### PR TITLE
Add support for Debian 10 and Debian unstable

### PR DESCRIPTION
**Pull request by gaborcsardi**
Mostly straightforward, I only had to modify one rule.

### CODE REVIEW

**Review by glin — APPROVED** [review]
:+1:, the CI failure is an unrelated issue with openSUSE (https://github.com/rstudio/r-system-requirements/pull/116)

**Comment by gaborcsardi** [comment]
> 👍, the CI failure is an unrelated issue with openSUSE 

Actually, do you mind if I change the tests to update the metadata only once? That would make them much faster I think and these failures would probably go away.

**Comment by gaborcsardi** [comment]
@glin oh, and thanks for the review!

**Comment by glin** [comment]
Hmm, could do we do that while still running every rule test in a clean container? Each rule runs in a fresh container to prevent previously installed repos from messing with subsequent tests. Maybe we could have GHA build an image with updated metadata without cleaning on every run, then remove the metadata update from the tests.

The tests used to update metadata once, but there were bugs that slipped through because of that (#115)

**Comment by gaborcsardi** [comment]
> Maybe we could have GHA build an image with updated metadata without cleaning on every run, then remove the metadata update from the tests.

Yeah, exactly.

**Pull request merged**
