### PR TITLE
Add Debian 11 support

### PR DESCRIPTION
**Pull request by gaborcsardi**
Is it beneficial to have better Debian support here?

### CODE REVIEW

**Review by glin — APPROVED** [review]
Looks good, and it's definitely beneficial to have Debian support (I guess addresses https://github.com/rstudio/r-system-requirements/issues/111).

The only catch is that Package Manager still doesn't support Debian at all, so we wouldn't be providing binary packages for it still. But system requirements support would be simple enough to add. Would you be consuming this data through the packagemanager.posit.co API, like through the existing functionality in pak/remotes? If so, we'll also need a change in Package Manager itself, but it would be a pretty easy one.

**Comment by gaborcsardi** [comment]
> Would you be consuming this data through the packagemanager.posit.co API, like through the existing functionality in pak/remotes?

I am not entirely sure yet, because the API is a bit limiting. Right now I collect the `SystemRequirements` fields for all package I want to install and the API gives me the commands to run for these. This is OK, but it would be nice to be able to query if these packages are already installed or not, so it would be nice to get the package names as well.

I am thinking that I'll download all rules from the git repo, I have now a fast way to do that, and then do my own matching. For now, until the API will be more sophisticated.

So no rush on putting this is P3M. 

OTOH if this PR can be merged without changing the package manager, that would be great, then I don't need to maintain a fork.

**Comment by gaborcsardi** [comment]
@glin Thanks for the review!

**Comment by glin** [comment]
Yes this PR can be merged, and downloading the raw git repo data is perfectly fine. I'll open an issue on the Package Manager side to add Debian and/or enhance the API.

**Pull request merged**
