### PR TITLE
Fix V8 on Fedora 38

### PR DESCRIPTION
**Pull request by gaborcsardi**
They have two versions of V8 now, this is one of them.

### CODE REVIEW

**Review by glin — APPROVED** [review]

**Comment by gaborcsardi** [comment]
@glin: Thanks!

**Comment by jeroen** [comment]
What is the other version? Is `v8-devel` no longer sufficient?

**Comment by gaborcsardi** [comment]
```
> dnf search v8
...
v8-10.2-devel.aarch64 : v8 - development headers
v8-9.4-devel.aarch64 : v8 - development headers
...
```

Yeah, it is an alias (or whatever they call it), but the way we run the tests does not seem to find it:
```
[root@d3b7b4045985 ~]# yum -C list -q v8-devel
Error: No matching Packages to list
```

There is probably a way to query this with dnf or yum, but IDK how.

**Comment by jeroen** [comment]
@sgallagher is this expected? Is there a way to automatically resolve `v8-devel` to the default one from the current distro?

**Comment by sgallagher** [comment]
```
[sgallagh@toolbox ~]$ yum repoquery --whatprovides v8-devel
Fedora rawhide openh264 (From Cisco) - x86_64                                                                                                                                        2.3 kB/s | 2.5 kB     00:01    
Fedora - Rawhide - Developmental packages for the next Fedora release                                                                                                                 19 MB/s |  66 MB     00:03    
Fedora - Modular Rawhide - Developmental packages for the next Fedora release                                                                                                        1.7 MB/s | 2.3 MB     00:01    
v8-10.2-devel-3:10.2.154.23-1.18.13.0.8.fc38.i686
v8-10.2-devel-3:10.2.154.23-1.18.13.0.8.fc38.x86_64
v8-9.4-devel-3:9.4.146.26-1.16.19.0.1.fc38.i686
v8-9.4-devel-3:9.4.146.26-1.16.19.0.1.fc38.x86_64
```

If I do `dnf install v8-devel`, it (correctly) gets `v8-10.2-devel`.

In theory, I could remove the `Provides: v8-devel = %{v8_epoch}:%{v8_version}-%{v8_release}` from the non-default one, but I don't know if that's the best approach.

FTR, `yum list` only lists the actual package names, not its virtual `Provides`. You should use the `repoquery` command I noted above, which will search all provided names.

**Comment by gaborcsardi** [comment]
Thank you! 

Changed back to the alias here: https://github.com/rstudio/r-system-requirements/pull/123

**Pull request merged**
