### PR TITLE
Add some sysreqs

### PR DESCRIPTION
**Pull request by colearendt**
This is my first pass at adding system requirements, and I think I did things right, but it has also been a while since I did them 😅Please let me know if there is anything I can do to make the review process easier!

### CODE REVIEW

**Comment by glin** [comment]
This looks great, thanks for adding these! At a glance, I think we just need to fix some missing system packages: Debian 8 doesn't appear to have libjq, CentOS 7 and 8 need EPEL for chromium, and CentOS 6 doesn't seem to have chromium, even in EPEL.

**Comment by glin** [comment]
Oh, one more issue after those - only CentOS/RHEL 7 have `jq-devel`, and it comes from EPEL. CentOS/RHEL 6 and 8 don't have jq-devel for some reason, in either EPEL or the PowerTools repo.

**Comment by colearendt** [comment]
Finally! Success! Apologies for the slow iteration cycles there 😄

**Comment by colearendt** [comment]
@glin I don't have privileges to merge - all good from my end - please merge when you're ready!

**Comment by glin** [comment]
@colearendt Sorry about that - you should have write access now.

**Pull request merged**
